### ISSUE TITLE
my computer shuts down every time i want to run my game

### ISSUE THREAD

**Issue by ThiagoMAcqua** [omicronrex/gms_scheduler_fix#4]
when i try to run a game with the DBGHELP.DLL set the computer shuts down, i have no idea why (i use GMS 1.4)

**Comment by omicronrex** [comment]
which game is that?

**Comment by ThiagoMAcqua** [comment]
nvm, I was referring to myself as a developer, I had not seen this part of the text
![image](https://user-images.githubusercontent.com/88409480/212497461-850aa6f2-de96-4d2c-b04a-a16470310f72.png)

**Comment by omicronrex** [comment]
oh okay then, still kinda weird lol
