### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by Kalspecalt** [omicronrex/gms_scheduler_fix#5]
Just wanted to say thank you for creating such an awesome and simple solution to an otherwise 'black box' of an issue. 

I have set up a monthly recurring donation of $3 + fees on the donation link. I know it's not much but I hope it helps

Just FYI, I recommend not using paypal for donations because they have been known to lock accounts with all the money in for no reason, and never release it again, with zero ability to contact any kind of support (a fun google rabbit hole to explore!).

**Comment by omicronrex** [comment]
Thank you! much appreciated. Also, I have to use paypal because it's the only international service that works in Brazil.
